 export const products = [
  {
    id: "prod_001",
    name: "AeroGlide Wireless Ergonomic Mouse",
    brand: "LogiTech",
    category: "Electronics",
    price: 59.99,
    rating: 4.7,
    reviewsCount: 1240,
    inStock: true,
    stockCount: 45,
    imageUrl: "https://unsplash.com",
    tags: ["Wireless", "Ergonomic", "Office"],
    description: "Ultra-precise wireless mouse designed with an ergonomic contour shape to reduce wrist strain during long work hours."
  },
  {
    id: "prod_002",
    name: "QuantumSound Active Noise-Cancelling Headphones",
    brand: "SonicWave",
    category: "Electronics",
    price: 189.50,
    rating: 4.9,
    reviewsCount: 812,
    inStock: true,
    stockCount: 12,
    imageUrl: "https://unsplash.com",
    tags: ["ANC", "Bluetooth", "Premium"],
    description: "Experience pure audio bliss with active noise cancellation and a rich 40-hour battery life capacity."
  },
  {
    id: "prod_003",
    name: "ThermalCore Stainless Steel Water Bottle",
    brand: "HydroFlask",
    category: "Fitness & Outdoors",
    price: 34.99,
    rating: 4.5,
    reviewsCount: 3402,
    inStock: true,
    stockCount: 110,
    imageUrl: "https://unsplash.com",
    tags: ["Insulated", "Eco-Friendly", "Gym"],
    description: "Double-walled vacuum insulated bottle that keeps your favorite beverages ice cold for up to 24 hours."
  },
  {
    id: "prod_004",
    name: "Veloce Carbon Fiber Road Bike Frame",
    brand: "Strada",
    category: "Fitness & Outdoors",
    price: 1249.00,
    rating: 4.8,
    reviewsCount: 45,
    inStock: false,
    stockCount: 0,
    imageUrl: "https://unsplash.com",
    tags: ["Cycling", "Carbon Fiber", "Pro"],
    description: "Feather-light professional carbon fiber frame designed for competitive aerodynamic efficiency and maximum speed."
  },
  {
    id: "prod_005",
    name: "BaristaPro Espresso Machine",
    brand: "Breville",
    category: "Home & Kitchen",
    price: 699.95,
    rating: 4.6,
    reviewsCount: 520,
    inStock: true,
    stockCount: 7,
    imageUrl: "https://unsplash.com",
    tags: ["Coffee", "Appliances", "Premium"],
    description: "Bring the cafe home with a built-in conical burr grinder, precise micro-foam milk texturing, and dynamic thermal control."
  },
  {
    id: "prod_006",
    name: "Lumina Smart LED Desk Lamp",
    brand: "GlowTech",
    category: "Home & Kitchen",
    price: 45.00,
    rating: 4.3,
    reviewsCount: 198,
    inStock: true,
    stockCount: 89,
    imageUrl: "https://unsplash.com",
    tags: ["Smart Home", "Lighting", "Minimalist"],
    description: "Dimmable smart lamp compatible with voice assistants, featuring multiple temperature settings for reading and focus."
  },
  {
    id: "prod_007",
    name: "Nomad Canvas Everyday Backpack",
    brand: "Trailblazer",
    category: "Apparel & Accessories",
    price: 75.00,
    rating: 4.4,
    reviewsCount: 615,
    inStock: true,
    stockCount: 34,
    imageUrl: "https://unsplash.com",
    tags: ["Travel", "Water-Resistant", "Unisex"],
    description: "Durable, water-resistant canvas backpack equipped with a padded 15-inch laptop sleeve and plenty of organization pockets."
  },
  {
    id: "prod_008",
    name: "Classic Chronograph Leather Watch",
    brand: "Horology",
    category: "Apparel & Accessories",
    price: 150.00,
    rating: 4.2,
    reviewsCount: 89,
    inStock: true,
    stockCount: 15,
    imageUrl: "https://unsplash.com",
    tags: ["Watches", "Leather", "Classic"],
    description: "Timeless quartz chronograph watch featuring a genuine top-grain Italian leather strap and scratch-proof sapphire crystal."
  },
  {
    id: "prod_009",
    name: "FocusFlow Ergonomic Office Chair",
    brand: "ZenSeat",
    category: "Office Supplies",
    price: 299.99,
    rating: 4.7,
    reviewsCount: 432,
    inStock: true,
    stockCount: 22,
    imageUrl: "https://unsplash.com",
    tags: ["Furniture", "Ergonomic", "Office"],
    description: "High-back mesh chair providing adjustable 3D lumbar support, multi-angle tilt lock, and dynamic 3D armrests."
  },
  {
    id: "prod_010",
    name: "TitanGrip Heavy-Duty Resistance Bands",
    brand: "IronFit",
    category: "Fitness & Outdoors",
    price: 24.95,
    rating: 4.5,
    reviewsCount: 1550,
    inStock: false,
    stockCount: 0,
    imageUrl: "https://unsplash.com",
    tags: ["Gym", "Home Workout", "Strength"],
    description: "Set of 5 premium natural latex resistance tubes with anti-snap technology and padded sweat-proof foam handles."
  }
];