spring.application.name=cms

# DB Connection
spring.datasource.url=jdbc:mysql://localhost:3306/cms_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=deepcoder

# Hibernate Settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl_auto=update

# Server Port
# server.port=8081
