spring.application.name=docker-app

# Configure h2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-name=org.h2.Driver

# Enable the H2 Web Console so you can see your data in a browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
